name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install JS deps
        run: |
          npm ci || npm i

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run -s test:pw

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Run Go tests with coverage
        run: |
          chmod +x scripts/run-go-tests.sh
          ./scripts/run-go-tests.sh

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-artifacts
          path: |
            **/coverage.out
            coverage/*.out
            sample-app/coverage.out
            algorithm-visualization/coverage.out
